### ISSUE TITLE
Crash on android 11 on returning result to onActivitity Result

### ISSUE THREAD

**Issue by faiz786** [Dhaval2404/ImagePicker#173]
there is crash on android 11 on returning result to onActivityResult 

I checked You Library Code it is using External Storage Directory There is restriction in android 11 on that

**Comment by GuilhE** [comment]
I've a [PR](https://github.com/Dhaval2404/ImagePicker/pull/171) open that fixes that (and more). Hope the owner finds it useful 🙏

**Comment by rahat14** [comment]
Author Should Fix This Soon !!

**Comment by abalta-mobven** [comment]
Thank you @GuilhE

**Comment by sinhpn92** [comment]
I have been looking for a long time, But seem to be not fixed. Right?

**Comment by GuilhE** [comment]
> I have been looking for a long time, But seem to be not fixed. Right?

Try my fork to see if it helps you. No problem so far on Pixel 3a running Android 11

**Comment by Damercy** [comment]
@GuilhE Awesome. Has the author merged the changes you've made in the fork? Would be great instead of cloning another repo. 😄

**Comment by GuilhE** [comment]
> @GuilhE Awesome. Has the author merged the changes you've made in the fork? Would be great instead of cloning another repo. 😄 

The PRs are open, auther said nothing so far. You don't have to fork, use jitpack: then I'm using this: https://jitpack.io/#GuilhE/ImagePicker

**Comment by Damercy** [comment]
@GuilhE I just checked the PR tab. Seems like there's some merge conflict and hence PR's not being merged? See [this](https://github.com/Dhaval2404/ImagePicker/pull/171#commitcomment-48856827).

**Comment by GuilhE** [comment]
> @GuilhE I just checked the PR tab. Seems like there's some merge conflict and hence PR's not being merged? See [this](https://github.com/Dhaval2404/ImagePicker/pull/171#commitcomment-48856827).
> 
> Anyway, thanks for your contribution. I'll probably use the above mentioned jitpack link that you provided. Thanks again!

Done, didn't noticed that merge conflict, thanks for point it out 👍

**Comment by yidinghe** [comment]
@GuilhE , there is another issue, Falied to create camera image file, Permission denied.

**Comment by GuilhE** [comment]
> @GuilhE , there is another issue, Falied to create camera image file, Permission denied. Should we change getExternalStoragePublicDirectory as well?

Have you tried this:
```
<manifest package="com.example">
    <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
    </queries>
    ...
</manifest>
```

**Comment by yidinghe** [comment]
Yes, I did. Have permission denied issue getCameraDirectory. Check the issue #186.

**Comment by HosseinKurd** [comment]
Same Issue!

**Comment by Dhaval2404** [comment]
The issue has been resolved in v2.0.
