### ISSUE TITLE
Not working in Samsung Galaxy A5

### ISSUE THREAD

**Issue by vkfan** [Dhaval2404/ImagePicker#23]
Image picker is not working in Samsung Galaxy A5. Android 6.0.1.
![15644938229312072698965603077218](https://user-images.githubusercontent.com/26092403/62133913-4411d480-b2fd-11e9-84c7-1b32590d9154.jpg)

**Comment by Dhaval2404** [comment]
@vkfan Which version you are currently using?

**Comment by vkfan** [comment]
> @vkfan Which version you are currently using?

support 1.3, the issue is when I try to choose images from downloads folder.

**Comment by Dhaval2404** [comment]
@vkfan Can you please try out the latest version.

**Comment by Dhaval2404** [comment]
The issue has been resolved on v1.4

**Comment by nipuncs** [comment]
#### The issue is still there on some mobile phones. Only for downloaded images.

- v1.7.1
- Nokia 2 (Android 9)

**Stack trace**
`E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Download/image-1.jpg (No such file or directory)`

`java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65560, result=-1, data=Intent { dat=file:///storage/emulated/0/Download/image-1.jpg (has extras) }} to activity `

**Code**
```
         ImagePicker.with(this)
            .compress(1024)
            .start { resultCode, data ->
                if (resultCode == Activity.RESULT_OK) {
                    try {
                        val file = ImagePicker.getFile(data)
                        if (file != null) {
                            val bitmap = BitmapFactory.decodeFile(file.absolutePath)
                            //Do my work
                        }
                    } catch (e: Exception) {
                       //Show Error
                    }
                } else {
                    //Show Error
                }
            }
```

**Comment by tgbmoseswebb** [comment]
I am getting the same issue as well on some devices.  Only causes issues when picking images from the "Download" folder. 

ImagePicker.with(this)
            .start { resultCode, data ->
                if (resultCode == Activity.RESULT_OK) {
                    //continued work
                } else if (resultCode == ImagePicker.RESULT_ERROR) {
                    //error
                } 
            }

**Comment by tushar-ifarmer** [comment]
I am also getting the error. Is it solved? I am using version 2.1
